import { Referral } from '@/types';

export const mockReferrals: Referral[] = [
  {
    id: 'REF-001',
    candidateName: 'Sarah Jenkins',
    candidateEmail: 'sarah.jenkins@example.com',
    candidatePhone: '+84 987 654 321',
    candidateLinkedin: 'linkedin.com/in/sarahjenkins',
    jobId: 'JOB-001',
    jobTitle: 'Senior Frontend Engineer',
    cvUrl: '/mock-cv/sarah_jenkins_cv.pdf',
    notes: 'Sarah có 5 năm kinh nghiệm làm việc với React và hệ sinh thái Frontend. Từng làm việc tại các công ty product lớn.',
    status: 'interview_2',
    totalPointsEarned: 35,
    submittedAt: '2026-03-28T09:00:00Z',
    updatedAt: '2026-04-01T10:00:00Z',
    iHiringApplicationId: 'IH-APP-001',
    timeline: [
      { status: 'screening',   label: 'Giới thiệu -> Sơ loại CV', date: '29/03/2026 14:30', completed: true,  note: 'TA đã duyệt CV và đánh giá phù hợp.', pointsAwarded: 10 },
      { status: 'interview_2', label: 'Đang phỏng vấn -> Offer',     date: '05/04/2026 15:00', completed: false, note: 'Lên lịch vòng cuối. Pass sẽ gửi Offer.' },
      { status: 'onboarded',   label: 'Onboarding',  date: '',                 completed: false, note: 'Thưởng 15đ khi ứng viên nhận việc.' },
    ],
  },
  {
    id: 'REF-002',
    candidateName: 'Michael Chen',
    candidateEmail: 'michael.chen@example.com',
    candidatePhone: '+84 912 345 678',
    candidateLinkedin: 'linkedin.com/in/michaelchen',
    jobId: 'JOB-002',
    jobTitle: 'Product Manager',
    cvUrl: '/mock-cv/mchen_pm_resume.pdf',
    notes: 'Michael rất mạnh về data-driven product management.',
    status: 'offer_sent',
    totalPointsEarned: 55,
    submittedAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-04-01T09:00:00Z',
    iHiringApplicationId: 'IH-APP-002',
    timeline: [
      { status: 'screening',   label: 'Giới thiệu -> Sơ loại CV', date: '16/03/2026 11:00', completed: true, note: 'TA đã duyệt CV.', pointsAwarded: 10 },
      { status: 'offer_sent',  label: 'Đang phỏng vấn -> Offer',  date: '01/04/2026 09:00', completed: true, note: 'Đã gửi Offer letter cho ứng viên.', pointsAwarded: 15 },
      { status: 'onboarded',   label: 'Onboarding',  date: 'Dự kiến 15/04',   completed: false, note: 'Chờ ứng viên confirm. +10đ khi onboard.' },
    ],
  },
  {
    id: 'REF-003',
    candidateName: 'Phạm Văn Đức',
    candidateEmail: 'phamvanduc@example.com',
    candidatePhone: '+84 901 234 567',
    jobId: 'JOB-004',
    jobTitle: 'Senior UI/UX Designer',
    notes: 'Anh Đức đang làm tại agency, muốn chuyển sang môi trường product.',
    status: 'screening',
    totalPointsEarned: 5,
    submittedAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
    timeline: [
      { status: 'screening', label: 'Giới thiệu -> Sơ loại CV', date: '01/04/2026 08:00', completed: true, note: 'CV đã gửi. Đang chờ TA xử lý sơ loại.', pointsAwarded: 5 },
      { status: 'interview_1', label: 'Đang phỏng vấn -> Offer', date: '', completed: false, note: '' },
      { status: 'onboarded',   label: 'Onboarding', date: '', completed: false, note: '' },
    ],
  },
];
