import { Job } from '@/types';

export const mockJobs: Job[] = [
  {
    id: 'JOB-001',
    title: 'Senior Backend Developer (Go/NodeJS)',
    department: 'Engineering',
    location: 'Hà Nội',
    type: 'Full-time',
    isHot: true,
    isActive: true,
    rewardPoints: 100,
    publishDate: '2026-03-15',
    iHiringJobId: 'IH-2026-001',
    referralCount: 3,
    description:
      'Tìm kiếm kỹ sư Backend có 3+ năm kinh nghiệm với Go hoặc NodeJS. Có kinh nghiệm làm việc với kiến trúc microservices, hệ thống high-traffic và tối ưu hóa database.',
    responsibilities: [
      'Thiết kế, xây dựng và bảo trì các API hiệu năng cao, có khả năng mở rộng.',
      'Tham gia vào quá trình thiết kế kiến trúc hệ thống (Microservices).',
      'Tối ưu hóa database (PostgreSQL, MongoDB, Redis) cho các hệ thống high-traffic.',
      'Làm việc chặt chẽ với team Frontend và Product để đưa ra giải pháp kỹ thuật tối ưu.',
      'Review code và hướng dẫn các thành viên junior trong team.',
    ],
    requirements: [
      'Ít nhất 3 năm kinh nghiệm lập trình Backend với Go hoặc NodeJS.',
      'Hiểu biết sâu sắc về cấu trúc dữ liệu, giải thuật và design patterns.',
      'Kinh nghiệm làm việc với Message Queue (Kafka, RabbitMQ) là một lợi thế.',
      'Quen thuộc với Docker, Kubernetes và môi trường CI/CD.',
    ],
    benefits: [
      'Mức lương cạnh tranh, review lương 2 lần/năm.',
      'Thưởng tháng 13, thưởng hiệu quả công việc (1-3 tháng lương).',
      'Bảo hiểm sức khỏe cao cấp (PVI/Bảo Việt).',
      'Trang bị Macbook Pro và màn hình rời.',
      'Môi trường làm việc trẻ trung, năng động, linh hoạt (Hybrid working).',
    ],
  },
  {
    id: 'JOB-002',
    title: 'Product Manager',
    department: 'Product',
    location: 'Hồ Chí Minh',
    type: 'Full-time',
    isHot: false,
    isActive: true,
    rewardPoints: 50,
    publishDate: '2026-03-18',
    iHiringJobId: 'IH-2026-002',
    referralCount: 1,
    description:
      'Quản lý vòng đời sản phẩm từ khâu lên ý tưởng đến khi ra mắt. Làm việc chặt chẽ với đội ngũ Engineering và Design.',
    responsibilities: [
      'Xây dựng và thực thi roadmap sản phẩm theo chiến lược công ty.',
      'Thu thập, phân tích yêu cầu từ khách hàng và stakeholders.',
      'Làm việc với Engineering để estimate, lên kế hoạch sprint.',
    ],
    requirements: [
      'Ít nhất 3 năm kinh nghiệm PM trong môi trường product tech.',
      'Kỹ năng phân tích dữ liệu, làm việc tốt với SQL cơ bản.',
      'Giao tiếp tiếng Anh tốt.',
    ],
    benefits: [
      'Lương thương lượng theo năng lực.',
      'Cổ phần ESOP cho nhân sự cấp cao.',
      'Budget học tập & phát triển bản thân.',
    ],
  },
  {
    id: 'JOB-003',
    title: 'Marketing Executive',
    department: 'Marketing',
    location: 'Hà Nội',
    type: 'Full-time',
    isHot: false,
    isActive: true,
    rewardPoints: 50,
    publishDate: '2026-03-20',
    iHiringJobId: 'IH-2026-003',
    referralCount: 2,
    description:
      'Lên kế hoạch và triển khai các chiến dịch digital marketing đa kênh. Yêu cầu ít nhất 1 năm kinh nghiệm trong lĩnh vực marketing công nghệ.',
    responsibilities: [
      'Lên kế hoạch và thực thi chiến dịch performance marketing.',
      'Quản lý content calendar trên các kênh social media.',
      'Phân tích số liệu, báo cáo hiệu quả chiến dịch.',
    ],
    requirements: [
      'Tốt nghiệp ngành Marketing, Truyền thông hoặc liên quan.',
      'Ít nhất 1 năm kinh nghiệm digital marketing.',
      'Thành thạo Google Ads, Meta Ads, công cụ phân tích.',
    ],
    benefits: [
      'Môi trường năng động, nhiều cơ hội học hỏi.',
      'Thưởng theo performance hàng quý.',
    ],
  },
  {
    id: 'JOB-004',
    title: 'Senior UI/UX Designer',
    department: 'Design',
    location: 'Hà Nội',
    type: 'Full-time',
    isHot: true,
    isActive: true,
    rewardPoints: 100,
    publishDate: '2026-03-22',
    iHiringJobId: 'IH-2026-004',
    referralCount: 0,
    description:
      'Thiết kế giao diện người dùng và tối ưu hóa trải nghiệm. Yêu cầu thành thạo Figma, có tư duy product-mindset.',
    responsibilities: [
      'Thiết kế UI/UX cho web và mobile app.',
      'Xây dựng và duy trì design system.',
      'Nghiên cứu người dùng, tổ chức usability testing.',
    ],
    requirements: [
      'Ít nhất 3 năm kinh nghiệm UI/UX.',
      'Thành thạo Figma, có portfolio ấn tượng.',
      'Hiểu biết về front-end development là lợi thế.',
    ],
    benefits: [
      'Lương cạnh tranh.',
      'Được tham gia các dự án product lớn.',
      'Ngân sách mua tools và khoá học.',
    ],
  },
  {
    id: 'JOB-005',
    title: 'Data Analyst',
    department: 'Data',
    location: 'Hồ Chí Minh',
    type: 'Full-time',
    isHot: false,
    isActive: true,
    rewardPoints: 50,
    publishDate: '2026-03-25',
    iHiringJobId: 'IH-2026-005',
    referralCount: 1,
    description:
      'Phân tích dữ liệu người dùng, xây dựng dashboard báo cáo và đưa ra các insight giúp cải thiện sản phẩm.',
    responsibilities: [
      'Xây dựng và bảo trì các dashboard báo cáo (Metabase, Looker Studio).',
      'Phân tích hành vi người dùng, đưa ra insight cho Product.',
      'Hỗ trợ A/B testing và phân tích kết quả thử nghiệm.',
    ],
    requirements: [
      'Thành thạo SQL, Python hoặc R.',
      'Kinh nghiệm với BI tools (Metabase, Tableau, Looker).',
      'Tư duy phân tích, chú ý đến chi tiết.',
    ],
    benefits: [
      'Được tiếp cận kho dữ liệu lớn, học hỏi nhiều từ thực tế.',
      'Lương cạnh tranh, thưởng performance.',
    ],
  },
];
